# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 11:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Adress', models.TextField()),
                ('Department', models.CharField(max_length=50)),
                ('Manager', models.CharField(max_length=20)),
                ('Work_Contact_Number', models.CharField(max_length=20)),
                ('Personal_Contact_Number', models.CharField(max_length=20)),
                ('Work_Email', models.CharField(max_length=30)),
                ('Personal_Email', models.CharField(max_length=30)),
                ('Date_Added_to_System', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
